language: python

python:
    - 3.7

sudo: required

before_install: 
    - bash prerequisites.sh
    - WORKDIR=`pwd`
    - sudo apt-get install -y liblzo2-dev

install:
    
    # python reqs
    - pip install pysam
    - pip install scipy
    - pip install bx-python
    - pip install scikit-bio

    ##LAST
    - wget https://github.com/adamewing/dep/blob/master/last-737.zip?raw=true -O last-737.zip
    - unzip last-737.zip
    - make CXXFLAGS=-O3 -C last-737 && sudo make install -C last-737
    ##BWA (newest version)
    - git clone https://github.com/lh3/bwa.git
    - sudo make -C bwa
    - sudo mv bwa/bwa $WORKDIR/bin
    ##HTSLIB
    - git clone https://github.com/samtools/htslib.git
    - sudo make -C htslib
    ##Samtools
    - git clone https://github.com/samtools/samtools.git
    - sudo make -C samtools
    - sudo mv samtools/samtools $WORKDIR/bin/
    - sudo mv samtools/misc/wgsim $WORKDIR/bin/
    ##Bcftools
    - git clone https://github.com/samtools/bcftools.git
    - sudo make -C bcftools
    - sudo mv bcftools/bcftools $WORKDIR/bin/
    ##Minia
    - wget http://gatb-tools.gforge.inria.fr/versions/bin/minia-2.0.3-Linux.tar.gz
    - tar -xvf minia-2.0.3-Linux.tar.gz
    - sudo mv minia-2.0.3-Linux/bin/{dbgh5,dbginfo,h5dump,minia}  $WORKDIR/bin/
    ##Exonerate
    - git clone https://github.com/adamewing/exonerate.git
    - cd exonerate
    - git checkout v2.4.0
    - autoreconf -i
    - ./configure --prefix=$WORKDIR && make && make check && make install
    - cd ..

    - export PATH=$WORKDIR/bin/:$PATH

script:
    ##Installing TEBreak, indexing the reference and running the test
    - tebreak/tebreak.py -b test/data/example.ins.bam  -r test/data/Homo_sapiens_chr4_50000000-60000000_assembly19.fasta -p 4 --pickle test/example.pickle --detail_out test/example.tebreak.detail.out
    - tebreak/resolve.py -p test/example.pickle -i lib/teref.human.fa --detail_out test/example.resolve.detail.out -t 4 -v -o test/example.tab.txt -r test/data/Homo_sapiens_chr4_50000000-60000000_assembly19.fasta
    - cd test
    - python checktest.py
